name: helpme
publish_to: 'none'
version: 0713.23.2+6

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_sign_in: ^6.1.4
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  pinput: ^2.2.31
  basic_utils: ^5.6.0
  flutter_native_splash: ^2.3.1
  provider: ^6.0.5
  google_nav_bar: ^5.0.6
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/l10n/

flutter_native_splash:
  image: assets/images/app_splash_logo.png
  image_dark: assets/images/app_splash_logo.png
  android: true
  ios: true
  fullscreen: true
  color: "#ffffff"
  color_dark: "#000000"

  android_12:
    branding: assets/images/transparent.png

flutter_launcher_icons:
  android: false
  ios: true
  image_path: assets/images/app_logo.png
